use anyhow::Result;
use crate::store::engagements;
use crate::store::findings;
use crate::store::cve;
use crate::store::evidence;
use crate::store::vault::VaultKey;

pub fn build_client_report(
    user_id: i64,
    key: Option<&VaultKey>,
    engagement_id: i64,
) -> Result<String> {
    let engagement = engagements::list_engagements(user_id)?
        .into_iter()
        .find(|e| e.id == engagement_id)
        .ok_or_else(|| anyhow::anyhow!("engagement not found"))?;

    let mut md = String::new();
    md.push_str("# Security Assessment Report\n\n");
    md.push_str(&format!("**Client:** {}\n", engagement.client_name));
    md.push_str(&format!("**Engagement:** {} - {}\n", engagement.client_name, engagement.engagement_type));
    md.push_str(&format!("**Status:** {}\n", engagement.status));
    md.push_str(&format!("**Window:** {} to {}\n\n", engagement.start_date, engagement.end_date));
    if !engagement.scope.is_empty() {
        md.push_str("## Scope\n\n");
        md.push_str(&engagement.scope);
        md.push_str("\n\n");
    }
    if !engagement.notes.is_empty() {
        md.push_str("## Engagement Notes\n\n");
        md.push_str(&engagement.notes);
        md.push_str("\n\n");
    }

    let all_findings = findings::list_findings_for_engagement(user_id, engagement_id)?;
    if all_findings.is_empty() {
        md.push_str("## Findings\n\nNo findings recorded for this engagement.\n\n");
    } else {
        md.push_str("## Findings\n\n");
        for f in &all_findings {
            md.push_str(&format!("### {}\n", f.title));
            md.push_str(&format!("- **Severity:** {}\n", f.severity));
            md.push_str(&format!("- **Status:** {}\n", f.status));
            md.push_str(&format!("- **CVSS:** {}\n", f.cvss));
            md.push_str(&format!("- **Reported:** {}\n\n", f.reported_at));
            if !f.description.is_empty() {
                md.push_str("#### Description\n\n");
                md.push_str(&f.description);
                md.push_str("\n\n");
            }
            if !f.remediation.is_empty() {
                md.push_str("#### Remediation\n\n");
                md.push_str(&f.remediation);
                md.push_str("\n\n");
            }
            if !f.affected_assets.is_empty() {
                md.push_str(&format!("#### Affected Assets\n\n{}\n\n", f.affected_assets));
            }
            if !f.evidence_ids.is_empty() {
                md.push_str(&format!("#### Evidence References\n\n{}\n\n", f.evidence_ids));
            }
            if !f.cve_ids.is_empty() {
                md.push_str(&format!("#### CVEs\n\n{}\n\n", f.cve_ids));
            }
        }
    }

    let cves = cve::list_cves(user_id)?;
    if !cves.is_empty() {
        md.push_str("## CVE Register\n\n");
        md.push_str("| CVE | Severity | CVSS | Fetched |\n");
        md.push_str("|-----|----------|------|---------|\n");
        for c in &cves {
            md.push_str(&format!("| {} | {} | {} | {} |\n", c.cve_id, c.severity, c.cvss_score, c.fetched_at));
        }
        md.push_str("\n");
    }

    if let Some(key) = key {
        match evidence::list_evidence(user_id, key) {
            Ok(items) if !items.is_empty() => {
                md.push_str("## Evidence Index\n\n");
                for item in &items {
                    md.push_str(&format!("- **{}** — {}\n", item.name, item.description.lines().next().unwrap_or("—")));
                }
                md.push_str("\n");
            }
            _ => {}
        }
    }

    md.push_str("---\n\n");
    md.push_str("*Report generated by Tsukuyomi OS*\n");
    Ok(md)
}

#[allow(dead_code)]
pub fn export_client_report(
    user_id: i64,
    key: Option<&VaultKey>,
    engagement_id: i64,
    path: &str,
) -> Result<()> {
    let report = build_client_report(user_id, key, engagement_id)?;
    std::fs::write(path, report)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[cfg(test)]
    fn temp_env() -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "tsukuyomi-report-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::env::set_var("LOCALAPPDATA", &dir);
        std::fs::create_dir_all(&dir).unwrap();
        crate::store::set_data_dir_for_tests(&dir);
        dir
    }

    #[test]
    fn report_build_smoke() {
        let dir = temp_env();
        let user_id = 1;

        crate::store::engagements::add_engagement(
            user_id,
            "Acme Corp",
            "Network Assessment",
            "10.0.0.0/24",
            "2026-07-01",
            "2026-07-03",
            "Completed",
            "BC-2026-001",
            "Initial scoping call on 2026-06-28.",
        )
        .unwrap();

        let engagement_id = crate::store::engagements::list_engagements(user_id).unwrap()[0].id;

        let report = build_client_report(user_id, None, engagement_id).unwrap();
        assert!(report.contains("# Security Assessment Report"));
        assert!(report.contains("Acme Corp"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
